# Generated by Django 4.2.6 on 2024-03-01 06:38

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User_details",
            fields=[
                ("Sl_no", models.IntegerField(primary_key=True, serialize=False)),
                ("Full_name", models.CharField(max_length=255)),
                ("Email", models.CharField(max_length=255)),
                ("Phone_number", models.IntegerField()),
                ("Password", models.CharField(max_length=255)),
            ],
        ),
    ]
