# Generated by Django 4.2.6 on 2024-03-11 11:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web_App", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Bike_details",
            fields=[
                ("Sl_no", models.IntegerField(primary_key=True, serialize=False)),
                ("Bike_name", models.CharField(max_length=255)),
                ("Bike_type", models.CharField(max_length=255)),
                ("Bike_price", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="House_details",
            fields=[
                ("Sl_no", models.IntegerField(primary_key=True, serialize=False)),
                ("House_name", models.CharField(max_length=255)),
                ("House_type", models.CharField(max_length=255)),
                ("House_location", models.CharField(max_length=255)),
                ("House_price", models.IntegerField()),
            ],
        ),
    ]
