# Generated by Django 4.2.6 on 2024-03-11 11:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web_App", "0002_bike_details_house_details"),
    ]

    operations = [
        migrations.CreateModel(
            name="Homestay_details",
            fields=[
                ("Sl_no", models.IntegerField(primary_key=True, serialize=False)),
                ("House_name", models.CharField(max_length=255)),
                ("House_type", models.CharField(max_length=255)),
                ("House_location", models.CharField(max_length=255)),
                ("House_price", models.IntegerField()),
                ("House_Phone", models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name="House_details",
        ),
    ]
