# Generated by Django 4.2.6 on 2024-03-11 11:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web_App", "0003_homestay_details_delete_house_details"),
    ]

    operations = [
        migrations.CreateModel(
            name="Bikestation_details",
            fields=[
                ("Sl_no", models.IntegerField(primary_key=True, serialize=False)),
                ("Bikestation_name", models.CharField(max_length=255)),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
                ("Bikestation_location", models.CharField(max_length=255)),
            ],
        ),
    ]
