# Generated by Django 4.2.6 on 2024-03-12 09:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web_App", "0005_bike_detail_delete_bike_details"),
    ]

    operations = [
        migrations.CreateModel(
            name="Bike_booking",
            fields=[
                ("Sl_no", models.IntegerField(primary_key=True, serialize=False)),
                ("Bikestation_name", models.CharField(max_length=255)),
                ("Bike_name", models.CharField(max_length=255)),
                ("Bike_price", models.IntegerField()),
                ("Rent_date", models.DateField()),
                ("Return_date", models.DateField(default="")),
                ("Status", models.CharField(max_length=255)),
            ],
        ),
    ]
