# Generated by Django 4.2.6 on 2024-03-12 10:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web_App", "0007_bike_book_delete_bike_booking"),
    ]

    operations = [
        migrations.CreateModel(
            name="Bike_books",
            fields=[
                ("Sl_no", models.IntegerField(primary_key=True, serialize=False)),
                ("User_name", models.CharField(max_length=255)),
                ("Bikestation_name", models.CharField(max_length=255)),
                ("Bike_name", models.CharField(max_length=255)),
                ("Bike_price", models.IntegerField()),
                ("Rent_date", models.CharField(max_length=255)),
                ("Return_date", models.CharField(default="", max_length=255)),
                ("Status", models.CharField(default="On Rent", max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name="Bike_book",
        ),
    ]
