# Generated by Django 4.2.6 on 2024-03-12 10:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web_App", "0008_bike_books_delete_bike_book"),
    ]

    operations = [
        migrations.AddField(
            model_name="bike_detail",
            name="Bike_availability",
            field=models.CharField(default="Available", max_length=255),
        ),
    ]
