# Generated by Django 4.2.6 on 2024-03-12 15:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web_App", "0009_bike_detail_bike_availability"),
    ]

    operations = [
        migrations.AddField(
            model_name="bike_books",
            name="total_amout",
            field=models.IntegerField(default=0),
        ),
    ]
