# Generated by Django 4.2.6 on 2024-03-13 05:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web_App", "0010_bike_books_total_amout"),
    ]

    operations = [
        migrations.CreateModel(
            name="Home_book",
            fields=[
                ("Sl_no", models.IntegerField(primary_key=True, serialize=False)),
                ("User_name", models.CharField(max_length=255)),
                ("Name", models.CharField(max_length=255)),
                ("Location", models.CharField(max_length=255)),
                ("Check_in", models.CharField(max_length=255)),
                ("Ckeck_out", models.CharField(max_length=255)),
                ("Rent", models.IntegerField()),
                ("Type", models.CharField(max_length=255)),
            ],
        ),
    ]
