# Generated by Django 4.2.6 on 2024-03-13 05:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web_App", "0011_home_book"),
    ]

    operations = [
        migrations.CreateModel(
            name="Feedback",
            fields=[
                ("Sl_no", models.IntegerField(primary_key=True, serialize=False)),
                ("User_name", models.CharField(max_length=255)),
                ("Feedback", models.CharField(max_length=255)),
            ],
        ),
    ]
