# Generated by Django 4.2.6 on 2024-04-05 04:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web_App", "0012_feedback"),
    ]

    operations = [
        migrations.CreateModel(
            name="Room_details",
            fields=[
                ("Sl_no", models.IntegerField(primary_key=True, serialize=False)),
                ("Home_stay", models.CharField(max_length=255)),
                ("Room_name", models.CharField(max_length=255)),
                ("Room_type", models.CharField(max_length=255)),
                ("Price", models.IntegerField()),
                ("Discription", models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name="homestay_details",
            name="House_price",
        ),
    ]
