# Generated by Django 4.2.6 on 2024-03-22 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_App', '0012_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='bike_detail',
            name='Bike_image',
            field=models.ImageField(blank=True, null=True, upload_to='bike_images/'),
        ),
    ]
