# Generated by Django 4.2.6 on 2024-04-06 02:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web_App", "0013_room_details_remove_homestay_details_house_price"),
    ]

    operations = [
        migrations.CreateModel(
            name="Home_book1",
            fields=[
                ("Sl_no", models.IntegerField(primary_key=True, serialize=False)),
                ("User_name", models.CharField(max_length=255)),
                ("Name", models.CharField(max_length=255)),
                ("Room_name", models.CharField(max_length=255)),
                ("Location", models.CharField(max_length=255)),
                ("Check_in", models.CharField(max_length=255)),
                ("Ckeck_out", models.CharField(max_length=255)),
                ("Rent", models.IntegerField()),
                ("Type", models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name="Home_book",
        ),
    ]
