# Generated by Django 4.2.6 on 2024-03-23 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_App', '0013_bike_detail_bike_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='homestay_details',
            name='House_image',
            field=models.ImageField(blank=True, null=True, upload_to='homestay_images/'),
        ),
    ]
