# Generated by Django 4.2.6 on 2024-04-22 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_App', '0014_home_book1_delete_home_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='bike_detail',
            name='Bike_image',
            field=models.ImageField(blank=True, null=True, upload_to='bike_images/'),
        ),
        migrations.AddField(
            model_name='homestay_details',
            name='House_image',
            field=models.ImageField(blank=True, null=True, upload_to='homestay_images/'),
        ),
    ]
