# Generated by Django 4.2.6 on 2024-04-24 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_App', '0015_bike_detail_bike_image_homestay_details_house_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='home_book1',
            old_name='Ckeck_out',
            new_name='Check_out',
        ),
    ]
