# Generated by Django 4.2.6 on 2024-04-22 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_App', '0014_homestay_details_house_image'),
        ('web_App', '0015_bike_detail_bike_image_homestay_details_house_image'),
    ]

    operations = [
    ]
