# Generated by Django 4.2.6 on 2024-04-24 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_App', '0016_merge_20240423_0018'),
        ('web_App', '0016_rename_ckeck_out_home_book1_check_out'),
    ]

    operations = [
    ]
