# Generated by Django 4.2.6 on 2024-05-12 08:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web_App', '0017_merge_20240424_1850'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homestay_details',
            name='House_image',
        ),
        migrations.CreateModel(
            name='HomestayImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='homestay_images/')),
                ('homestay', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='web_App.homestay_details')),
            ],
        ),
    ]
