# Generated by Django 4.2.6 on 2024-05-12 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_App', '0018_remove_homestay_details_house_image_homestayimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='homestay_details',
            name='House_image',
            field=models.ImageField(blank=True, null=True, upload_to='homestay_images/'),
        ),
        migrations.DeleteModel(
            name='HomestayImage',
        ),
    ]
