# Generated by Django 4.2.6 on 2024-05-12 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_App', '0019_homestay_details_house_image_delete_homestayimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='room_details',
            name='Room_image',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
